### ISSUE TITLE
RAM usage in modal instance launch

### ISSUE THREAD

**Issue by millerjs** [LabAdvComp/tukey_portal#95]
When launching a new instance, ram usage is in the details table is displayed as `RAM | Displaying 7 items MB`
![screen shot 2015-01-09 at 11 16 04 am](https://cloud.githubusercontent.com/assets/4062890/5683892/4cfdb6f8-97f1-11e4-81ef-5063d4e60825.png)

**Comment by philloooo** [comment]
Can't reproduce this bug.
